security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

                # login success redirecting options (read further below)
                always_use_default_target_path: true
                default_target_path: /admin/dashboard
                target_path_parameter: _target_path
                use_referer: true
                use_forward: false
            logout:
                path:   /logout
                target: /login
                invalidate_session: false
            anonymous:    true

        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_FINANCE, ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_READER, ROLE_CUSTOMER_CARE, ROLE_OPERATIONS, ROLE_SONATA_USER_READER, ROLE_SONATA_USER_ADMIN, ROLE_SONATA_TRANSACTION_READER, ROLE_SONATA_TRANSACTION_ADMIN, ROLE_SONATA_TRANSACTION_LOG_READER, ROLE_SHOW_BALANCE] }

    role_hierarchy:
        ROLE_SONATA_TRANSACTION_READER: [ROLE_SONATA_ADMIN_TRANSACTION_LIST, ROLE_SONATA_ADMIN_TRANSACTION_VIEW, ROLE_SONATA_ADMIN_TRANSACTION_EXPORT, ROLE_SONATA_ADMIN]
        ROLE_SONATA_TRANSACTION_ADMIN: [ROLE_SONATA_TRANSACTION_READER, ROLE_SONATA_ADMIN_TRANSACTION_DELETE, ROLE_SONATA_ADMIN_TRANSACTION_CREATE, ROLE_SONATA_ADMIN_TRANSACTION_EDIT]

        ROLE_SONATA_AUDIT_READER: [ROLE_SONATA_ADMIN_AUDIT_LIST, ROLE_SONATA_ADMIN_AUDIT_VIEW, ROLE_SONATA_ADMIN_AUDIT_EXPORT, ROLE_SONATA_ADMIN]
        ROLE_SONATA_AUDIT_ADMIN: [ROLE_SONATA_AUDIT_READER, ROLE_SONATA_ADMIN_AUDIT_DELETE, ROLE_SONATA_ADMIN_AUDIT_CREATE, ROLE_SONATA_ADMIN_AUDIT_EDIT]

        ROLE_SONATA_TRANSACTION_LOG_READER: [ROLE_SONATA_ADMIN, ROLE_SONATA_ADMIN_TRANSACTION_LOG_LIST, ROLE_SONATA_ADMIN_TRANSACTION_LOG_VIEW, ROLE_SONATA_ADMIN_TRANSACTION_LOG_EXPORT]
        ROLE_SONATA_TRANSACTION_LOG_ADMIN: [ROLE_SONATA_TRANSACTION_LOG_READER, ROLE_SONATA_ADMIN_TRANSACTION_LOG_DELETE, ROLE_SONATA_ADMIN_TRANSACTION_LOG_CREATE, ROLE_SONATA_ADMIN_TRANSACTION_LOG_EDIT]

        ROLE_SONATA_USER_READER: [ROLE_SONATA_ADMIN, ROLE_SONATA_ADMIN_USER_LIST, ROLE_SONATA_ADMIN_USER_VIEW, ROLE_SONATA_ADMIN_USER_EXPORT]
        ROLE_SONATA_USER_ADMIN: [ROLE_SONATA_USER_READER, ROLE_SONATA_ADMIN_USER_DELETE, ROLE_SONATA_ADMIN_USER_CREATE, ROLE_SONATA_ADMIN_USER_EDIT]

        ROLE_SONATA_REFILL_AMOUNT_LOG_READER: [ROLE_SONATA_ADMIN_REFILL_AMOUNT_LOG_LIST, ROLE_SONATA_ADMIN_REFILL_AMOUNT_LOG_VIEW, ROLE_SONATA_ADMIN_REFILL_AMOUNT_LOG_EXPORT]
        ROLE_SONATA_REFILL_AMOUNT_LOG_ADMIN: [ROLE_SONATA_REFILL_AMOUNT_LOG_READER, ROLE_SONATA_ADMIN_REFILL_AMOUNT_LOG_DELETE, ROLE_SONATA_ADMIN_REFILL_AMOUNT_LOG_CREATE, ROLE_SONATA_ADMIN_REFILL_AMOUNT_LOG_EDIT]

        ROLE_SONATA_REFILL_AMOUNT_READER: [ROLE_SONATA_ADMIN_REFILL_AMOUNT_LIST, ROLE_SONATA_ADMIN_REFILL_AMOUNT_VIEW, ROLE_SONATA_ADMIN_REFILL_AMOUNT_EXPORT]
        ROLE_SONATA_REFILL_AMOUNT_ADMIN: [ROLE_SONATA_REFILL_AMOUNT_READER, ROLE_SONATA_ADMIN_REFILL_AMOUNT_CREATE, ROLE_SONATA_ADMIN_REFILL_AMOUNT_EDIT]
        ROLE_SONATA_ACCOUNT_REPORT_READER: [ROLE_SONATA_ADMIN, ROLE_SONATA_ADMIN_ACCOUNT_REPORT_LIST, ROLE_SONATA_ADMIN_ACCOUNT_REPORT_VIEW, ROLE_SONATA_ADMIN_ACCOUNT_REPORT_EXPORT]
        ROLE_SONATA_ACCOUNT_REPORT_ADMIN: [ROLE_SONATA_ACCOUNT_REPORT_READER, ROLE_SONATA_ADMIN_ACCOUNT_REPORT_DELETE, ROLE_SONATA_ADMIN_ACCOUNT_REPORT_CREATE, ROLE_SONATA_ADMIN_ACCOUNT_REPORT_EDIT]

        ROLE_SHOW_BALANCE: [ROLE_VIEW_BALANCE, ROLE_SONATA_ADMIN]
        ROLE_READER: [ROLE_SONATA_TRANSACTION_READER, ROLE_SONATA_AUDIT_READER, ROLE_SONATA_TRANSACTION_LOG_READER, ROLE_SONATA_ADMIN,ROLE_SONATA_REFILL_AMOUNT_READER]
        ROLE_FINANCE: [ROLE_SONATA_ACCOUNT_REPORT_READER, ROLE_VIEW_BALANCE, ROLE_SONATA_REFILL_AMOUNT_ADMIN]
        ROLE_CUSTOMER_CARE: [ROLE_SONATA_TRANSACTION_READER]
        ROLE_OPERATIONS: [ROLE_READER, ROLE_SONATA_TRANSACTION_ADMIN]
        ROLE_ADMIN: [ROLE_READER, ROLE_SONATA_TRANSACTION_ADMIN, ROLE_SONATA_AUDIT_ADMIN, ROLE_SONATA_TRANSACTION_LOG_ADMIN, ROLE_SONATA_USER_ADMIN,ROLE_SONATA_SUPPLIER_LOG_ADMIN,ROLE_SONATA_REFILL_AMOUNT_LOG_ADMIN,ROLE_SONATA_REFILL_AMOUNT_ADMIN,ROLE_SONATA_ACCOUNT_REPORT_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]